## **벡터**
- 벡터는 숫자를 원소로 가지는 리스트 또는 배열이다.
- 벡터는 공간에서 한 점을 나타낸다.
- 벡터는 원점으로부터 상대적 위치를 표현한다.
- 벡터에 숫자를 곱해주면 길이만 변한다.
- 1보다 크면 길이가 늘어나고, 1보다 작으면 길이가 줄어든다. 0보다 작으면 반대 방향이 된다.

In [1]:
import numpy as np

In [2]:
x = np.array([1, 7, 2])
y = np.array([5, 2, 1])

In [3]:
x + y

array([6, 9, 3])

In [4]:
x - y

array([-4,  5,  1])

In [5]:
x * y

array([ 5, 14,  2])

### **벡터의 노름**
- 원점에서부터의 거리
- L1 노름은 각 성분의 변화량의 절대값을 모두 더한다.
- L2 노름은 피타고라스 정리를 이용해 유클리드 거리를 계산한다.
- L2 노름은 np.linalg.norm을 이용

In [7]:
def l1_norm(x):
    x_norm = np.abs(x)
    x_norm = np.sum(x_norm)
    return x_norm

def l2_norm(x):
    x_norm = x*x
    x_norm = np.sum(x_norm)
    x_norm = np.sqrt(x_norm)
    return x_norm

### **두 벡터 사이의 거리**
- 두 벡터 사이의 거리를 계산할 때는 벡터의 뺄셈을 이용한다.

### **두 벡터 사이의 각도**
- 제2 코사인 법칙에 의해 두 벡터 사이의 각도를 계산할 수 있다.

In [8]:
def angle(x, y):
    v = np.inner(x, y) / (l2_norm(x) * l2_norm(y))
    theta = np.arccos(v)
    return theta